// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjSHGKtEaYe7-s9YkCFnwbB6WXg9UzU0I',
    appId: '1:884072391627:web:e60be82aa667f1609a8c4e',
    messagingSenderId: '884072391627',
    projectId: 'rivrpod-clean-architecture',
    authDomain: 'rivrpod-clean-architecture.firebaseapp.com',
    storageBucket: 'rivrpod-clean-architecture.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMFNoRnYJzED20diLsBIICpvyf_0IKsK4',
    appId: '1:884072391627:android:3ca3332d2e9a20ea9a8c4e',
    messagingSenderId: '884072391627',
    projectId: 'rivrpod-clean-architecture',
    storageBucket: 'rivrpod-clean-architecture.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwh21mqEeuCgDNQrKsMpaxMyofYi4yKIc',
    appId: '1:884072391627:ios:d91d57ccc8ac7bd19a8c4e',
    messagingSenderId: '884072391627',
    projectId: 'rivrpod-clean-architecture',
    storageBucket: 'rivrpod-clean-architecture.appspot.com',
    iosClientId: '884072391627-94aob6f2af4301rljfi85i5h1eg9aium.apps.googleusercontent.com',
    iosBundleId: 'com.flutterApp.movies.riverpodCleanArchitecture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwh21mqEeuCgDNQrKsMpaxMyofYi4yKIc',
    appId: '1:884072391627:ios:d91d57ccc8ac7bd19a8c4e',
    messagingSenderId: '884072391627',
    projectId: 'rivrpod-clean-architecture',
    storageBucket: 'rivrpod-clean-architecture.appspot.com',
    iosClientId: '884072391627-94aob6f2af4301rljfi85i5h1eg9aium.apps.googleusercontent.com',
    iosBundleId: 'com.flutterApp.movies.riverpodCleanArchitecture',
  );
}
